modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "minedevice"
version = "${version}"
displayName = "MineDevice"
authors = "SamSu255"
description = '''

Adds a usable megaphone item that applies a voice filter through Plasmo Voice.
'''
#logoFile = ""

[[dependencies.minedevice]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.minedevice]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.minedevice]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.minedevice]]
modId = "plasmovoice"
mandatory = false
versionRange = "[0,)"
ordering = "AFTER"
side = "CLIENT"
